application: placingliterature
version: default
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^utils/*

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/images

- url: /css
  static_dir: static/styles

- url: /js
  static_dir: static/scripts

- url: /pages
  static_dir: static/pages

- url: /about
  script: handlers.home.app

- url: /funding
  script: handlers.home.app

- url: /home
  script: handlers.home.app

- url: /newhome
  script: handlers.home.app

- url: /map(/?.*)
  script: handlers.home.app

- url: /all
  script: handlers.home.app
  login: admin

- url: /places/add
  script: handlers.places.app

- url: /places/show
  script: handlers.places.app

- url: /places/info/(.*)
  script: handlers.places.app

- url: /places/visit/(.*)
  script: handlers.places.app

- url: /places/export
  script: handlers.places.app
  login: admin

- url: /places/recent
  script: handlers.places.app

- url: /places/allbydate
  script: handlers.places.app
  login: admin

- url: /places/count
  script: handlers.places.app

- url: /places/authors
  script: handlers.places.app

- url: /places/titles
  script: handlers.places.app

- url: /places/dump
  script: handlers.export.app
  login: admin

- url: /places/import
  script: handlers.export.app

- url: /places/csv_import/(.*)
  script: handlers.export.app
  login: admin

- url: /places/missing_books
  script: handlers.export.app

- url: /blog/update
  script: handlers.blogposts.app
  login: admin

- url: /user/status
  script: handlers.home.app

- url: /places/query/(.*)
  script: handlers.places.app

- url: /place/(.*)
  script: handlers.place.app

- url: /isbndb/book_import
  script: handlers.isbn.app

- url: /update_books
  script: handlers.update_scenes.app
  login: admin

- url: /update_isbns
  script: handlers.update_scenes.app
  login: admin

- url: /reset_isbns
  script: handlers.update_scenes.app
  login: admin

- url: /collections/(.*)
  script: handlers.collections.app


- url: .*
  script: handlers.home.app


libraries:
- name: webapp2
  version: "2.5.1"
